// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKMpClw6REjWwh9vyGV6AxjEYm9j-wkSk',
    appId: '1:704246927124:web:c1d6885e5d21ebdbe2bc01',
    messagingSenderId: '704246927124',
    projectId: 'smart-clothing-app-34e1f',
    authDomain: 'smart-clothing-app-34e1f.firebaseapp.com',
    storageBucket: 'smart-clothing-app-34e1f.appspot.com',
    measurementId: 'G-W9JQ5CLCFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoip1wZFpsl1-P6BXirgPTj418KAleepQ',
    appId: '1:704246927124:android:e6e44a21961362f2e2bc01',
    messagingSenderId: '704246927124',
    projectId: 'smart-clothing-app-34e1f',
    storageBucket: 'smart-clothing-app-34e1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFKVwA7Nf8VsYw2j31emnHlhQk8zC5cw',
    appId: '1:704246927124:ios:59c90684ab8ff8c6e2bc01',
    messagingSenderId: '704246927124',
    projectId: 'smart-clothing-app-34e1f',
    storageBucket: 'smart-clothing-app-34e1f.appspot.com',
    iosBundleId: 'com.example.smartclothingproject',
  );
}
